project_id = "cpushnwxfdvqlglzhxcb"

[functions.add-video]
verify_jwt = false

[functions.generate-category-image]
verify_jwt = false

[functions.get-categories-with-images]
verify_jwt = false

[functions.update-category-image]
verify_jwt = false

[functions.migrate-tags-to-categories]
verify_jwt = false