// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zupbpzlqeysrinicwuls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cGJwemxxZXlzcmluaWN3dWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDAxOTQsImV4cCI6MjA2NTc3NjE5NH0.GzyFJi-fyIl1aID84oV9ThQO3Cn8_zCkPSVql13fdR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});