// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpushnwxfdvqlglzhxcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwdXNobnd4ZmR2cWxnbHpoeGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzE1ODYsImV4cCI6MjA2ODQ0NzU4Nn0.FwVkpeqLI4ZiNI2FeYD4Z2fPCzhzHWbLiuuAQQ1ltMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});